### ISSUE TITLE
Application.php onTick() uses JobStatistic which was removed in recent merge

### ISSUE THREAD

**Issue by gogis79** [eymengunay/EoJobQueueBundle#3]
So whole thing stopped working entrely

Job 57d97ace279871e7718b4567:   [Symfony\Component\Debug\Exception\ClassNotFoundException]
Job 57d97ace279871e7718b4567:   Attempted to load class "JobStatistic" from namespace "Eo\JobQueueBundle\Document".
Job 57d97ace279871e7718b4567:   Did you forget a "use" statement for another namespace?

**Comment by eymengunay** [comment]
Hello @gogis79 ,

`JobStastic` class is removed at 4a8090bcb77d8efa8aa77649f43cb31c09d906ca.

You can use 18fb3cbb0b50b9951112331055ac97b29c512742 (last commit before this change) to fix the problem.

`dev-master#18fb3cbb0b50b9951112331055ac97b29c512742`

**Comment by gogis79** [comment]
Thank you for quick reply. I disabled statistics through eo_job_queue.statistics: false
