### ISSUE TITLE
registerBundles error in README.md

### ISSUE THREAD

**Issue by hegwout** [eymengunay/EoJobQueueBundle#5]
`new Eo\EoJobQueueBundle\EoJobQueueBundle(),`
should be :
`new Eo\JobQueueBundle\EoJobQueueBundle(),`

**Comment by eymengunay** [comment]
Thank you @heoffice for the heads up! 👍 

https://github.com/eymengunay/EoJobQueueBundle/commit/fc672ce10d11cb921352599f23828780ceec56ef
